zanimaux_zanimaux_homepage:
    path:     /
    defaults: { _controller: ZanimauxZanimauxBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: ZanimauxZanimauxBundle:Default:layout }
Accueil:
    path:     /Accueil
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Accueil }
Profil:
    path:     /Profil
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Profil }
Adoption:
    path:     /Adoption
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Adoption }
Produit:
    path:     /Produit
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Produit }
Commande:
    path:     /Commande
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Commande }
Quizb:
    path:     /Quizb
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Quizb }
Blog:
    path:     /Blog
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Blog }
Promotion:
    path:     /Promotion
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Promotion }
Livraison:
    path:     /Livraison
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Livraison }
Zanimaux:
    path:     /Zanimaux
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Zanimaux }
Rechercher:
    path:     /Rechercher
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Rechercher }
Adopter:
    path:     /Adopter
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Adopter }
Adherer:
    path:     /Adherer
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Adherer }
Blogger:
    path:     /Blogger
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Blogger }
Apropos:
    path:     /Apropos
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Apropos }
Contact:
    path:     /Contact
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Contact }
Quiz:
    path:     /Quiz
    defaults: { _controller: ZanimauxZanimauxBundle:Default:Quiz }